# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development: 
  url: <% ENV['DATABASE_URL'] %>
  adapter: postgresql
  pool: 5
  timeout: 5000

production:
  url: <% ENV['DATABASE_URL'] %>
  adapter: postgresql
  pool: 5
  timeout: 5000

